// <auto-generated />
using System;
using FermentationControl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FermentationControl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626003008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("FermentationControl.Api.Models.Beer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("FermentationControl.Api.Models.FermentationParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExtractMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExtractMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PHMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PHMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TemperatureMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TemperatureMin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeerId")
                        .IsUnique();

                    b.ToTable("FermentationParameters");
                });

            modelBuilder.Entity("FermentationControl.Api.Models.FermentationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BeerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Extract")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PH")
                        .HasColumnType("TEXT");

                    b.Property<int>("TankId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("TankId");

                    b.ToTable("FermentationRecords");
                });

            modelBuilder.Entity("FermentationControl.Api.Models.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("FermentationControl.Api.Models.FermentationParameter", b =>
                {
                    b.HasOne("FermentationControl.Api.Models.Beer", "Beer")
                        .WithOne("FermentationParameter")
                        .HasForeignKey("FermentationControl.Api.Models.FermentationParameter", "BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");
                });

            modelBuilder.Entity("FermentationControl.Api.Models.FermentationRecord", b =>
                {
                    b.HasOne("FermentationControl.Api.Models.Beer", "Beer")
                        .WithMany("FermentationRecords")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FermentationControl.Api.Models.Tank", "Tank")
                        .WithMany("FermentationRecords")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FermentationControl.Api.Models.Beer", b =>
                {
                    b.Navigation("FermentationParameter");

                    b.Navigation("FermentationRecords");
                });

            modelBuilder.Entity("FermentationControl.Api.Models.Tank", b =>
                {
                    b.Navigation("FermentationRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
